# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - feathrregistry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://xcacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_66c04d46927e4262894a896b2ea25553 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_131d20b1c74c438bafd259f8f7ff7a66 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: xcacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_66c04d46927e4262894a896b2ea25553 }}/windoze/feathr-registry:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'feathrregistry'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_34c39d2cd8b44581b1789d6b34454b8e }}
        images: 'xcacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_66c04d46927e4262894a896b2ea25553 }}/windoze/feathr-registry:${{ github.sha }}'