[package]
name = "common-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenv = "0.15"
