# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Registry app

on:
  push:
    branches:
      - main
    paths:
      - "registry/**"
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://xcacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4da0dc091a964a20a1cbb1a8d1e4dff9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_666bc4a7427e436dbb000198bdbd5e35 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: xcacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4da0dc091a964a20a1cbb1a8d1e4dff9 }}/xcacr/windoze/feathr-registry:${{ github.sha }}
        context: ./registry
        # file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'feathrregistry'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f4848ae6b2dc4f42b8e56187d283fca4 }}
        images: 'xcacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4da0dc091a964a20a1cbb1a8d1e4dff9 }}/xcacr/windoze/feathr-registry:${{ github.sha }}'